language: elixir
cache:
  directories:
  - deps
  - _build
elixir:
  - 1.8.0
otp_release:
  - 21.0
env:
  global:
    - MIX_ENV=test
    - MAIN_BRANCHES="master"
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - "mix format --dry-run --check-formatted"
  - "mkdir /etc/sitrep && cp sitrep-config.json /etc/sitrep/config.json"
  - "mix test --exclude pending --trace --no-start"
  - "mix coveralls.travis --no-start"