language: elixir
cache:
  directories:
  - deps
  - _build
elixir:
  - 1.8.0
otp_release:
  - 21.0
env:
  global:
    - MIX_ENV=test
    - CONFIG_PATH=alertlytics-config.json
    - MAIN_BRANCHES="master"
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - "mix format --dry-run --check-formatted"
  - "mix test --exclude pending --trace"
  - "mix coveralls.travis"