---
version: '2'
services:
  alertlytics:
    container_name: alertlytics
    volumes:
    - ".:/home/app"
    build: "."
    env_file:
      - .env
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
  web:
    container_name: web
    image: kitematic/hello-world-nginx