version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.2.0
workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: 'docker.io/cultivatedcode/alertlytics:latest'
          timeout: '300'
      - anchore/parse_reports

