version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.0.0
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - checkout
      - run:
          name: build container
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:ci -f Dockerfile.prod .
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci
          timeout: '500'
          analysis_fail: True


#           # Elixir CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-elixir/ for more details
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version here
#       - image: circleci/elixir:1.4

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/postgres:9.4

#     working_directory: ~/repo
#     steps:
#       - checkout

#       # specify any bash command here prefixed with `run: `
#       - run: mix deps.get
#       - run: mix ecto.create
#       - run: mix test