name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.prod --tag localbuild/alertlytics:latest
    - name: Scan image
      uses: anchore/scan-action@v1
      with:
        image-reference: "localbuild/alertlytics:latest"
        dockerfile-path: "Dockerfile.prod"
        fail-build: true
        acs-report-enable: true
    - name: Anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: Anchore action SARIF report
      run: cat results.sarif
    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cultivatedcode/alertlytics
        dockerfile: Dockerfile.prod
        tag_with_ref: true
        tag_with_sha: true  
