name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.prod --tag cultivatedcode/alertlytics:$(date +%s)
    - name: Tag and Push
      run: |
        docker tag cultivatedcode/alertlytics:$(date +%s) docker.io/cultivatedcode/alertlytics:$(date +%s)
        docker push docker.io/cultivatedcode/alertlytics:$(date +%s)
      
